# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'codepath-flickz' do
  use_frameworks!
  # Pods for codepath-flickz
  pod 'AFNetworking'
  pod 'SVProgressHUD', '~> 2.1'
  pod 'MBProgressHUD'
end
